
generation_settings:
  tags: null
  temperature: 0.0
  timeout: null
  top_k: null
  top_p: null
  transport: null
  verbose: null

safety_settings:
  HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
  HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
  HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
  HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_LOW_AND_ABOVE
