gemini_platform:
  - Gemini 2.0 Flash: gemini-2.0-flash-exp
  - Gemini 1.5 Pro: gemini-1.5-pro
  - Gemini 1.5 Flash: gemini-1.5-flash
  - Gemini 1.0 Pro: gemini-1.0-pro
  # - Gemma 2 9B: gemma-2-9b-it
  # - Gemma 2 27B: gemma-2-27b-it

openai_platform:
  - GPT 3.5 Turbo: gpt-3.5-turbo-instruct

groq_platform:
  - Llama 3.2 3B: llama-3.2-3b-preview
  - Llama 3.1 70B: llama-3.1-70b-versatile
  - Llama 3.1 8B: llama-3.1-8b-instant
  - Llama3 70B 8192: llama3-70b-8192
  - Llama3 8B 8192: llama3-8b-8192
  - Gemma 7B IT: gemma-7b-it
  - Mixtral 8x7B 32768: mixtral-8x7b-32768

anthropic_platform:
  - Claude 3.5 Sonnet: claude-3-5-sonnet-20240620
  - Claude 3 Opus: claude-3-opus-20240229
  - Claude 3 Sonnet: claude-3-sonnet-20240229
  - Claude 3 Haiku: claude-3-haiku-20240307

deepinfra_platform:
  - Meta Llama 3 70B Instruct: meta-llama/Meta-Llama-3-70B-Instruct
  - Meta Llama 3 8B Instruct: meta-llama/Meta-Llama-3-8B-Instruct
  - Mixtral 8x22B Instruct v0.1: mistralai/Mixtral-8x22B-Instruct-v0.1
  - WizardLM 2 8x22B: microsoft/WizardLM-2-8x22B
  - WizardLM 2 7B: microsoft/WizardLM-2-7B
  - Gemma 1.1 7B IT: google/gemma-1.1-7b-it
  - Airoboros 70B: deepinfra/airoboros-70b

nvidia_platform:
  - Deepseek R1: deepseek-ai/deepseek-r1
  - Llama 3.3 70B: meta/llama-3.3-70b-instruct

ollama_platform:
  - Phi 3: phi3
  - Llama 3.1 8B: llama3.1
  - Llama 3.2 3B: llama3.2
  - Qwen 2: qwen2
  - Nemotron Mini: nemotron-mini
  - Mixtral: mistral:latest
  - Deepseek R1 8B: deepseek-r1:8b
